### YamlMime:ManagedReference
items:
- uid: MB.Common.Settings.ListingSettings.ListingSettingsHelper
  commentId: T:MB.Common.Settings.ListingSettings.ListingSettingsHelper
  id: ListingSettingsHelper
  parent: MB.Common.Settings.ListingSettings
  children:
  - MB.Common.Settings.ListingSettings.ListingSettingsHelper.GetSelectedListingDto(System.String)
  langs:
  - csharp
  - vb
  name: ListingSettingsHelper
  nameWithType: ListingSettingsHelper
  fullName: MB.Common.Settings.ListingSettings.ListingSettingsHelper
  type: Class
  source:
    href: https://github.com/MicroBIM-DevTeam/MB.Common/blob/03427dd60ca1ecd255dc2b7bcbc47cd343703f2f/Settings/ListingSettings/ListingSettingsHelper.cs
  assemblies:
  - MB.Common
  namespace: MB.Common.Settings.ListingSettings
  summary: >-
    Provides helper methods for working with listing settings, including retrieval of <xref href="MB.Common.Settings.ListingSettings.ListingDto" data-throw-if-not-resolved="false"></xref> objects

    based on family and type information.
  example: []
  syntax:
    content: public static class ListingSettingsHelper
    content.vb: Public Module ListingSettingsHelper
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
- uid: MB.Common.Settings.ListingSettings.ListingSettingsHelper.GetSelectedListingDto(System.String)
  commentId: M:MB.Common.Settings.ListingSettings.ListingSettingsHelper.GetSelectedListingDto(System.String)
  id: GetSelectedListingDto(System.String)
  parent: MB.Common.Settings.ListingSettings.ListingSettingsHelper
  langs:
  - csharp
  - vb
  name: GetSelectedListingDto(string)
  nameWithType: ListingSettingsHelper.GetSelectedListingDto(string)
  fullName: MB.Common.Settings.ListingSettings.ListingSettingsHelper.GetSelectedListingDto(string)
  type: Method
  source:
    href: https://github.com/MicroBIM-DevTeam/MB.Common/blob/03427dd60ca1ecd255dc2b7bcbc47cd343703f2f/Settings/ListingSettings/ListingSettingsHelper.cs
  assemblies:
  - MB.Common
  namespace: MB.Common.Settings.ListingSettings
  summary: >-
    Retrieves the <xref href="MB.Common.Settings.ListingSettings.ListingDto" data-throw-if-not-resolved="false"></xref> that matches the specified family name and type from the user listing

    settings.
  example: []
  syntax:
    content: public static ListingDto? GetSelectedListingDto(string familyNameAndType)
    parameters:
    - id: familyNameAndType
      type: System.String
      description: The combined family name and type to search for.
    return:
      type: MB.Common.Settings.ListingSettings.ListingDto
      description: >-
        The <xref href="MB.Common.Settings.ListingSettings.ListingDto" data-throw-if-not-resolved="false"></xref> that matches the specified <code class="paramref">familyNameAndType</code>, or <code>null</code> if

        no match is found

        or if the user listing settings could not be loaded.
    content.vb: Public Shared Function GetSelectedListingDto(familyNameAndType As String) As ListingDto
  overload: MB.Common.Settings.ListingSettings.ListingSettingsHelper.GetSelectedListingDto*
  nameWithType.vb: ListingSettingsHelper.GetSelectedListingDto(String)
  fullName.vb: MB.Common.Settings.ListingSettings.ListingSettingsHelper.GetSelectedListingDto(String)
  name.vb: GetSelectedListingDto(String)
references:
- uid: MB.Common.Settings.ListingSettings.ListingDto
  commentId: T:MB.Common.Settings.ListingSettings.ListingDto
  parent: MB.Common.Settings.ListingSettings
  isExternal: true
  href: MB.Common.Settings.ListingSettings.ListingDto.html
  name: ListingDto
  nameWithType: ListingDto
  fullName: MB.Common.Settings.ListingSettings.ListingDto
- uid: MB.Common.Settings.ListingSettings
  commentId: N:MB.Common.Settings.ListingSettings
  isExternal: true
  href: MB.html
  name: MB.Common.Settings.ListingSettings
  nameWithType: MB.Common.Settings.ListingSettings
  fullName: MB.Common.Settings.ListingSettings
  spec.csharp:
  - uid: MB
    name: MB
    isExternal: true
    href: MB.html
  - name: .
  - uid: MB.Common
    name: Common
    isExternal: true
    href: MB.Common.html
  - name: .
  - uid: MB.Common.Settings
    name: Settings
    isExternal: true
    href: MB.Common.Settings.html
  - name: .
  - uid: MB.Common.Settings.ListingSettings
    name: ListingSettings
    isExternal: true
    href: MB.Common.Settings.ListingSettings.html
  spec.vb:
  - uid: MB
    name: MB
    isExternal: true
    href: MB.html
  - name: .
  - uid: MB.Common
    name: Common
    isExternal: true
    href: MB.Common.html
  - name: .
  - uid: MB.Common.Settings
    name: Settings
    isExternal: true
    href: MB.Common.Settings.html
  - name: .
  - uid: MB.Common.Settings.ListingSettings
    name: ListingSettings
    isExternal: true
    href: MB.Common.Settings.ListingSettings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: MB.Common.Settings.ListingSettings.ListingSettingsHelper.GetSelectedListingDto*
  commentId: Overload:MB.Common.Settings.ListingSettings.ListingSettingsHelper.GetSelectedListingDto
  isExternal: true
  href: MB.Common.Settings.ListingSettings.ListingSettingsHelper.html#MB_Common_Settings_ListingSettings_ListingSettingsHelper_GetSelectedListingDto_System_String_
  name: GetSelectedListingDto
  nameWithType: ListingSettingsHelper.GetSelectedListingDto
  fullName: MB.Common.Settings.ListingSettings.ListingSettingsHelper.GetSelectedListingDto
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
shouldSkipMarkup: true
