### YamlMime:ManagedReference
items:
- uid: MB.Common.Settings.ListingSettings.FittingGroupHelper
  commentId: T:MB.Common.Settings.ListingSettings.FittingGroupHelper
  id: FittingGroupHelper
  parent: MB.Common.Settings.ListingSettings
  children:
  - MB.Common.Settings.ListingSettings.FittingGroupHelper.GetPdfGroupName(MB.Common.Settings.ListingSettings.StandardFittingType)
  langs:
  - csharp
  - vb
  name: FittingGroupHelper
  nameWithType: FittingGroupHelper
  fullName: MB.Common.Settings.ListingSettings.FittingGroupHelper
  type: Class
  source:
    href: https://github.com/MicroBIM-DevTeam/MB.Common/blob/03427dd60ca1ecd255dc2b7bcbc47cd343703f2f/Settings/ListingSettings/FittingGroupHelper.cs
  assemblies:
  - MB.Common
  namespace: MB.Common.Settings.ListingSettings
  summary: >-
    Provides helper methods for grouping <xref href="MB.Common.Settings.ListingSettings.StandardFittingType" data-throw-if-not-resolved="false"></xref> values

    into their corresponding PDF group names for listing and reporting purposes.
  example: []
  syntax:
    content: public static class FittingGroupHelper
    content.vb: Public Module FittingGroupHelper
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
- uid: MB.Common.Settings.ListingSettings.FittingGroupHelper.GetPdfGroupName(MB.Common.Settings.ListingSettings.StandardFittingType)
  commentId: M:MB.Common.Settings.ListingSettings.FittingGroupHelper.GetPdfGroupName(MB.Common.Settings.ListingSettings.StandardFittingType)
  id: GetPdfGroupName(MB.Common.Settings.ListingSettings.StandardFittingType)
  parent: MB.Common.Settings.ListingSettings.FittingGroupHelper
  langs:
  - csharp
  - vb
  name: GetPdfGroupName(StandardFittingType)
  nameWithType: FittingGroupHelper.GetPdfGroupName(StandardFittingType)
  fullName: MB.Common.Settings.ListingSettings.FittingGroupHelper.GetPdfGroupName(MB.Common.Settings.ListingSettings.StandardFittingType)
  type: Method
  source:
    href: https://github.com/MicroBIM-DevTeam/MB.Common/blob/03427dd60ca1ecd255dc2b7bcbc47cd343703f2f/Settings/ListingSettings/FittingGroupHelper.cs
  assemblies:
  - MB.Common
  namespace: MB.Common.Settings.ListingSettings
  summary: Gets the PDF group name for a specified <xref href="MB.Common.Settings.ListingSettings.StandardFittingType" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: public static string GetPdfGroupName(StandardFittingType type)
    parameters:
    - id: type
      type: MB.Common.Settings.ListingSettings.StandardFittingType
      description: The fitting type to evaluate.
    return:
      type: System.String
      description: >-
        The group name as a <xref href="System.String" data-throw-if-not-resolved="false"></xref> if the type is recognized; otherwise, <code>null</code>.

        Possible group names include "Threaded Fittings", "Grooved Fittings", "Welded Fittings",

        "IGS Fittings", "Flanged Fittings", and "Loose Outlets".
    content.vb: Public Shared Function GetPdfGroupName(type As StandardFittingType) As String
  overload: MB.Common.Settings.ListingSettings.FittingGroupHelper.GetPdfGroupName*
references:
- uid: MB.Common.Settings.ListingSettings.StandardFittingType
  commentId: T:MB.Common.Settings.ListingSettings.StandardFittingType
  parent: MB.Common.Settings.ListingSettings
  isExternal: true
  href: MB.Common.Settings.ListingSettings.StandardFittingType.html
  name: StandardFittingType
  nameWithType: StandardFittingType
  fullName: MB.Common.Settings.ListingSettings.StandardFittingType
- uid: MB.Common.Settings.ListingSettings
  commentId: N:MB.Common.Settings.ListingSettings
  isExternal: true
  href: MB.html
  name: MB.Common.Settings.ListingSettings
  nameWithType: MB.Common.Settings.ListingSettings
  fullName: MB.Common.Settings.ListingSettings
  spec.csharp:
  - uid: MB
    name: MB
    isExternal: true
    href: MB.html
  - name: .
  - uid: MB.Common
    name: Common
    isExternal: true
    href: MB.Common.html
  - name: .
  - uid: MB.Common.Settings
    name: Settings
    isExternal: true
    href: MB.Common.Settings.html
  - name: .
  - uid: MB.Common.Settings.ListingSettings
    name: ListingSettings
    isExternal: true
    href: MB.Common.Settings.ListingSettings.html
  spec.vb:
  - uid: MB
    name: MB
    isExternal: true
    href: MB.html
  - name: .
  - uid: MB.Common
    name: Common
    isExternal: true
    href: MB.Common.html
  - name: .
  - uid: MB.Common.Settings
    name: Settings
    isExternal: true
    href: MB.Common.Settings.html
  - name: .
  - uid: MB.Common.Settings.ListingSettings
    name: ListingSettings
    isExternal: true
    href: MB.Common.Settings.ListingSettings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: MB.Common.Settings.ListingSettings.FittingGroupHelper.GetPdfGroupName*
  commentId: Overload:MB.Common.Settings.ListingSettings.FittingGroupHelper.GetPdfGroupName
  isExternal: true
  href: MB.Common.Settings.ListingSettings.FittingGroupHelper.html#MB_Common_Settings_ListingSettings_FittingGroupHelper_GetPdfGroupName_MB_Common_Settings_ListingSettings_StandardFittingType_
  name: GetPdfGroupName
  nameWithType: FittingGroupHelper.GetPdfGroupName
  fullName: MB.Common.Settings.ListingSettings.FittingGroupHelper.GetPdfGroupName
shouldSkipMarkup: true
