name: Build and Deploy DocFX to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if your default branch is not main

permissions:
  contents: write  # This gives the action permission to push to gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'  # Or whatever version you need

      - name: Install DocFX
        run: dotnet tool install -g docfx

      - name: Build Docs
        run: docfx build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./_site
